In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential, Model
from keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Flatten, Input, Concatenate
from keras.preprocessing.image import ImageDataGenerator

In [2]:
face_train_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

eyes_train_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

mouth_train_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

face_test_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

eyes_test_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

mouth_test_gen = ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    brightness_range=(0.5, 0.6),
)

In [3]:
face_train_generator = face_train_gen.flow_from_directory(
    'data/train/face_train/',
    target_size=(38, 38),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 776 images belonging to 7 classes.


In [4]:
eyes_train_generator = eyes_train_gen.flow_from_directory(
    'data/train/eyes_train/',
    target_size=(30, 62),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 777 images belonging to 7 classes.


In [5]:
mouth_train_generator = mouth_train_gen.flow_from_directory(
    'data/train/mouth_train/',
    target_size=(30, 38),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 769 images belonging to 7 classes.


In [6]:
face_valid_generator = face_test_gen.flow_from_directory(
    'data/test/face_test/',
    target_size=(38, 38),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 181 images belonging to 7 classes.


In [7]:
eyes_valid_generator = eyes_test_gen.flow_from_directory(
    'data/test/eyes_test/',
    target_size=(30, 62),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 181 images belonging to 7 classes.


In [8]:
mouth_valid_generator = mouth_test_gen.flow_from_directory(
    'data/test/mouth_test/',
    target_size=(30, 38),
    batch_size=64,
    color_mode="grayscale",
    class_mode="categorical"
)

Found 181 images belonging to 7 classes.


In [9]:
#mean

face_emotion_model = Sequential()

face_emotion_model.add(Conv2D(6, kernel_size=(3, 3), activation='relu', input_shape=(38, 38, 1), name="conv_1"))
face_emotion_model.add(MaxPooling2D(pool_size=(2, 2), name="pool_1"))

face_emotion_model.add(Conv2D(16, kernel_size=(3, 3), activation='relu', input_shape=(18, 18, 6), name="conv_2"))
face_emotion_model.add(MaxPooling2D(pool_size=(2, 2), name="pool_2"))

face_emotion_model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(8, 8, 1), name="conv_3"))
face_emotion_model.add(MaxPooling2D(pool_size=(2, 2), name="pool_3"))

face_emotion_model.add(Flatten(name="face_flatten"))

face_emotion_model.add(Dense(1024, activation='relu'))
face_emotion_model.add(Dropout(0.25))

face_emotion_model.add(Dense(7, activation='softmax'))

face_emotion_model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=0.0001, decay=1e-6), metrics=['accuracy'])

face_emotion_model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv_1 (Conv2D)             (None, 36, 36, 6)         60        
                                                                 
 pool_1 (MaxPooling2D)       (None, 18, 18, 6)         0         
                                                                 
 conv_2 (Conv2D)             (None, 16, 16, 16)        880       
                                                                 
 pool_2 (MaxPooling2D)       (None, 8, 8, 16)          0         
                                                                 
 conv_3 (Conv2D)             (None, 6, 6, 32)          4640      
                                                                 
 pool_3 (MaxPooling2D)       (None, 3, 3, 32)          0         
                                                                 
 face_flatten (Flatten)      (None, 288)              

In [10]:
# face_train = face_emotion_model.fit(
#     face_train_generator,
#     steps_per_epoch= 776 // 64,
#     epochs=50,
#     validation_data=face_valid_generator,
#     validation_steps= 181 // 64  
# )

In [11]:
# print("Training:", face_train.history['accuracy'][-1])
# print("Validation:", face_train.history['val_accuracy'][-1])

# plt.plot(face_train.history['accuracy'], label='Training Accuracy')
# plt.plot(face_train.history['val_accuracy'], label='Validation Accuracy')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.legend()
# plt.show()

In [12]:
face_model = Model(inputs=face_emotion_model.input, outputs=face_emotion_model.get_layer('face_flatten').output)

feature_face_train = face_model.predict(face_train_generator)

feature_face_valid = face_model.predict(face_valid_generator)


3/3 [==============================] - 0s 27ms/step


In [13]:
feature_face_train

array([[0.        , 0.00245339, 0.        , ..., 0.        , 0.        ,
        0.03110036],
       [0.        , 0.00517613, 0.        , ..., 0.        , 0.        ,
        0.03522938],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04287435],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04252308],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.03368181],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04280861]], dtype=float32)

In [14]:
feature_face_valid

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02830746],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.05173616],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.03486076],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0223485 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04946333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.04737936]], dtype=float32)

In [15]:
# variance

eyes_emotion_model = Sequential()

eyes_emotion_model.add(Conv2D(6, kernel_size=(3, 3), activation='relu', input_shape=(30, 62, 1)))
eyes_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

eyes_emotion_model.add(Conv2D(16, kernel_size=(3, 3), activation='relu', input_shape=(14, 30, 6)))
eyes_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

eyes_emotion_model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(6, 14, 16)))
eyes_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

eyes_emotion_model.add(Flatten(name="eyes_flatten"))

eyes_emotion_model.add(Dense(1024, activation='relu'))
eyes_emotion_model.add(Dropout(0.25))

eyes_emotion_model.add(Dense(7, activation='softmax'))

eyes_emotion_model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=0.0001, decay=1e-6), metrics=['accuracy'])

eyes_emotion_model.summary()

Model: "sequential_1"


_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 60, 6)         60        
                                                                 
 max_pooling2d (MaxPooling2  (None, 14, 30, 6)         0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 12, 28, 16)        880       
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 6, 14, 16)         0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 4, 12, 32)         4640      
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 2, 6, 32)          0         
 g2D)     

In [16]:
# eyes_train = eyes_emotion_model.fit(
#     eyes_train_generator,
#     steps_per_epoch= 777 // 64,
#     epochs=50,
#     validation_data=eyes_valid_generator,
#     validation_steps= 181 // 64  
# )

In [17]:
# print("Training:", eyes_train.history['accuracy'][-1])
# print("Validation:", eyes_train.history['val_accuracy'][-1])

# plt.plot(eyes_train.history['accuracy'], label='Training Accuracy')
# plt.plot(eyes_train.history['val_accuracy'], label='Validation Accuracy')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.legend()
# plt.show()

In [18]:
eyes_feature = Model(inputs=eyes_emotion_model.input, outputs=eyes_emotion_model.get_layer('eyes_flatten').output)
eyes_feature_train = eyes_feature.predict(eyes_train_generator)
eyes_feature_valid = eyes_feature.predict(eyes_valid_generator)


3/3 [==============================] - 0s 31ms/step


In [19]:
eyes_feature_train

array([[0.04376709, 0.023609  , 0.        , ..., 0.05474539, 0.07716968,
        0.00398259],
       [0.09100535, 0.03196906, 0.00227964, ..., 0.08558277, 0.10613824,
        0.0085912 ],
       [0.06681338, 0.01503857, 0.        , ..., 0.07793393, 0.12560228,
        0.01218364],
       ...,
       [0.01066854, 0.00771782, 0.0033514 , ..., 0.03693666, 0.08430764,
        0.01056295],
       [0.04906712, 0.03956955, 0.0261808 , ..., 0.09602828, 0.11424114,
        0.00456636],
       [0.03126717, 0.04145439, 0.02919935, ..., 0.05949473, 0.08304261,
        0.01442613]], dtype=float32)

In [20]:
eyes_feature_valid

array([[0.02444472, 0.01477559, 0.        , ..., 0.07625221, 0.13626257,
        0.0175816 ],
       [0.04574183, 0.019925  , 0.        , ..., 0.0480895 , 0.06982556,
        0.01407338],
       [0.04755373, 0.03046231, 0.        , ..., 0.06361931, 0.07749621,
        0.        ],
       ...,
       [0.08632728, 0.01847691, 0.        , ..., 0.05485454, 0.08748418,
        0.00604607],
       [0.05603281, 0.02585249, 0.0074098 , ..., 0.04312242, 0.07905745,
        0.00450944],
       [0.08342797, 0.03281652, 0.        , ..., 0.08078352, 0.11223079,
        0.00988454]], dtype=float32)

In [21]:
# variance

mouth_emotion_model = Sequential()

mouth_emotion_model.add(Conv2D(6, kernel_size=(3, 3), activation='relu', input_shape=(30, 38, 1)))
mouth_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

mouth_emotion_model.add(Conv2D(16, kernel_size=(3, 3), activation='relu', input_shape=(14, 18, 6)))
mouth_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

mouth_emotion_model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(6, 8, 16)))
mouth_emotion_model.add(MaxPooling2D(pool_size=(2, 2)))

mouth_emotion_model.add(Flatten(name="mouth_flatten"))

mouth_emotion_model.add(Dense(1024, activation='relu'))
mouth_emotion_model.add(Dropout(0.25))

mouth_emotion_model.add(Dense(7, activation='softmax'))

mouth_emotion_model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=0.0001, decay=1e-6), metrics=['accuracy'])

mouth_emotion_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 28, 36, 6)         60        
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 14, 18, 6)         0         
 g2D)                                                            
                                                                 
 conv2d_4 (Conv2D)           (None, 12, 16, 16)        880       
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 6, 8, 16)          0         
 g2D)                                                            
                                                                 
 conv2d_5 (Conv2D)           (None, 4, 6, 32)          4640      
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 2, 3, 32)         

In [22]:
# mouth_train = mouth_emotion_model.fit(
#     mouth_train_generator,
#     steps_per_epoch= 769 // 64,
#     epochs=50,
#     validation_data=mouth_valid_generator,
#     validation_steps= 181 // 64  
# )

In [23]:
# print("Training:", mouth_train.history['accuracy'][-1])
# print("Validation:", mouth_train.history['val_accuracy'][-1])

# plt.plot(mouth_train.history['accuracy'], label='Training Accuracy')
# plt.plot(mouth_train.history['val_accuracy'], label='Validation Accuracy')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.legend()
# plt.show()

In [24]:
mouth_feature = Model(inputs=mouth_emotion_model.input, outputs=mouth_emotion_model.get_layer('mouth_flatten').output)
mouth_feature_train = mouth_feature.predict(mouth_train_generator)
mouth_feature_valid = mouth_feature.predict(mouth_valid_generator)


3/3 [==============================] - 0s 23ms/step


In [25]:
mouth_feature_train

array([[0.        , 0.06550719, 0.        , ..., 0.        , 0.01006788,
        0.02155416],
       [0.        , 0.05277343, 0.        , ..., 0.        , 0.        ,
        0.0051724 ],
       [0.        , 0.08732902, 0.        , ..., 0.        , 0.01102345,
        0.        ],
       ...,
       [0.        , 0.07799639, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.05635453, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.05523759, 0.        , ..., 0.        , 0.03310424,
        0.        ]], dtype=float32)

In [26]:
mouth_feature_valid

array([[0.        , 0.03669132, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.09890766, 0.        , ..., 0.        , 0.01336046,
        0.        ],
       [0.05000618, 0.10205302, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.06253731, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.03359886, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06784614, 0.        , ..., 0.        , 0.        ,
        0.01256201]], dtype=float32)

In [27]:
concatenate_feature = Concatenate([feature_face_train, feature_face_valid, 
                                   eyes_feature_train, eyes_feature_valid, 
                                   mouth_feature_train, mouth_feature_valid])

In [28]:
all_feature_model = Sequential()
all_feature_model.add(concatenate_feature)

all_feature_model.add(Dense(864, activation='relu'))
all_feature_model.add(Dropout(0.5))
all_feature_model.add(Dense(7, activation='softmax'))

all_feature_model.compile(loss='categorical_crossentropy', 
                          optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=0.0001, decay=1e-6), 
                          metrics=['accuracy'])


In [29]:
# all_feature_model.summary()